### ISSUE TITLE
[bug?] オンラインセーブが完了するまでの時間が長い

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#103]
## 不具合内容
- 「Save」でキーフレーズを入れて「OK」を押した後に
セーブ完了メッセージが返ってくるまでの時間が長くなっているように感じます。
いつ頃からかは不明ですが、少なくともver3.1.7で起きています。
- 一度キーフレーズを空にしてクリップボードコピーしたときは問題ありません。
また、クリップボードコピーした後に「Save」からキーフレーズを入れて「OK」を押した場合は
速度的に問題ないようです。初回ロード時のみ発生するように感じます。

<img src="https://user-images.githubusercontent.com/44026291/170287844-3de1559e-0121-4379-98d1-ffe95b1efcf0.png" width="50%">

## 本来想定される動作
- キーフレーズの可否によらず、セーブ完了メッセージが瞬時に返ってくる。

## 確認環境
エディターバージョン：3.1.7
確認したキー数：12key
Windows 11 (x64) 、Chrome 103.0.5060.13（Official Build）dev （64 ビット）

**Comment by superkuppabros** [comment]
これは https://github.com/superkuppabros/danoni-editor/commit/decf9252c18926cb726ac91cc6a479c37216fc03 由来で、もともとオンラインセーブ時に、セーブの成功失敗に関係なく完了メッセージが出るようになっていました。
それをセーブの完了を待つようにしたので、メッセージが返ってくるまで時間がかかるようになっているものだと思います。
オンラインセーブ自体はそこまで連発するようなものでもないと思うのでこの仕様で特に問題ないかな…と思っていました。

**Comment by cwtickle** [comment]
実際にオンラインセーブ（オンラインロード）を待つように変えたためということですね、了解しました。
実害はないのですが、メッセージが返ってこないのでセーブを複数回押してしまい、
押した数だけメッセージが返ってくるというのがあるにはありました。

優先度は低くて良いと思いますが、オンラインセーブ（ロード）時にボタンを一時非表示にするとか
画面を暗転するなどすればわかりやすくなるのではと思いました。

**Comment by superkuppabros** [comment]
9d0e754 で実装しました。
こんな感じでどうでしょうか。

**Comment by cwtickle** [comment]
ありがとうございます。挙動、問題ありません。
Issueクローズしておきます。
