### ISSUE TITLE
[proposed] 4分譜面出力(Test)時の対象レーン制御

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#105]
## 要望内容
- 4分譜面出力(Test)時、現状は一番左のレーンに対して4分譜面を作成していますが、
別のレーンに出せるようにしたいです。
- Option Settingで対象レーンを数字で指定するイメージです。（左からn番目）

## 機能を必要とする理由
- キーによっては一番左が押しにくい位置にある場合があり、
一時的にキーコンやリバースすればいいのかもしれませんが手間に感じるときがあるため。

## 参考
- 参考に旧Flash版のエディターの機能イメージを載せます。
繰り返しパターンはBPMが速いときに使っていましたが、優先度としては落としても問題ありません。

<img src="https://user-images.githubusercontent.com/44026291/209487116-2f36b548-2634-4251-a704-2c836e9a36b3.png" width="90%">

<img src="https://user-images.githubusercontent.com/44026291/209487093-31ceb8fa-447f-4b25-b441-6f5f28695289.png" width="90%">

**Comment by superkuppabros** [comment]
https://github.com/superkuppabros/danoni-editor/commit/2b9c7cfa3ff7a92dc398c43bd823a005aed759a3
遅くなりましたが一応実装しました。

**Comment by cwtickle** [comment]
確認遅くなりました。ありがとうございました m(_ _)m
