### ISSUE TITLE
エディタ定義が入っていない状態でセーブデータを読み込むとエディタが落ちる

### ISSUE THREAD

**Issue by prlg25** [superkuppabros/danoni-editor#111]
# 期待される挙動
  - エディタ定義が入っていない状態でセーブデータ(オンラインセーブ、クリップボード)を読み込むと、エラー文が出力される
    - xxxkeyのキー定義が登録されていません　など
# 実際の挙動
  - エディタ定義が入っていない状態でセーブデータ(オンラインセーブ、クリップボード)を読み込むと、エディタが落ちる（表示されなくなる）
  - keyConfig[keyKind]がundefinedなのでエラーが出ているっぽい
![image](https://github.com/superkuppabros/danoni-editor/assets/99570135/421b85e0-abeb-45bb-86d2-3d917be6d032)
![image](https://github.com/superkuppabros/danoni-editor/assets/99570135/76b00f6d-15be-4d32-8e9e-5b88cf546eaf)
![image](https://github.com/superkuppabros/danoni-editor/assets/99570135/d5063bd4-572a-49a7-9fb4-b9da4539ea39)

# 再現手順
  - 手元で簡単に再現できるので21ikeyを使っていますが21iであることに特に意味はないです、21i以外でも起こりました 
  - 21iのキー定義が入っていない状態にする
  - 以下のセーブデータを読み込む(オンラインセーブ、クリップボード両方NGでした)
  ```
  {"blankFrame":200,"timings":[{"label":1,"startNum":0,"bpm":140}],"scoreNumber":1,"scores":[{"speeds":[],"notes":[[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0],[0]],"freezes":[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]}],"keyKind":"21i"}
  ```
# 環境
  - Win11 vivaldi 6.4.3160.47 (Stable channel) (64-bit) 
  - Edge(バージョン 119.0.2151.93 (公式ビルド) (64 ビット))でも確認

**Comment by superkuppabros** [comment]
多分上のPRで解決出来たと思います。遅くなりました
