### ISSUE TITLE
node-canvasの導入が大変なので変えたい

### ISSUE THREAD

**Issue by suzme** [superkuppabros/danoni-editor#118]
devDependenciesにcanvasが入っていますが、インストール時に[いろいろ導入しないといけない](https://github.com/Automattic/node-canvas/wiki/Installation:-Windows)のがちょっと大変です。
以前はnpm installだけで入ったと思うのですが(たまたま導入済だっただけ？)

コンパイル不要で動く[@napi-rs/canvas](https://www.npmjs.com/package/@napi-rs/canvas)という代替があるので、これを使うのがよさそうです。
↓こんな感じでよいはず
```
npm uninstall canvas
npm i -D @napi-rs/canvas
npm i -D canvas@npm:@napi-rs/canvas
```

参考：[ネイティブモジュールに依存しない node-canvas 代替ライブラリを使う - mizdra&#39;s blog](https://www.mizdra.net/entry/2023/01/22/232956)

テスト通るのは確認しましたが、いろいろ落ち着いてからのほうがいいと思うので一旦issueにします。

**Comment by superkuppabros** [comment]
ありがとうございます、#121 で実施しました。
