### ISSUE TITLE
[proposed] 現位置のフレーム数・時間、小節番号表示

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#13]
## 要望内容
1. 現在選択位置（ページ先頭）のフレーム数と時間、小節番号を表示して欲しいです。
※下記のようなイメージです。
![image](https://user-images.githubusercontent.com/44026291/83943424-fe843900-a836-11ea-8f54-e30c5faf2d18.png)

2. 現在設定中の入力間隔（8分、16分、32分、・・・）と１間隔あたりのフレーム数（小数点1桁まで）を表示して欲しいです。

## 機能を必要とする理由
1. ダンおに（CW Edition）では色変化、歌詞表示等を行う際、変化点のフレーム数が必要です。
その際に、どの位置に置けばいいかのフレーム数があると助かります。
また譜面ズレがあったり、演出タイミングの違和感を見るのに
プレイ上では時間表示（3:50など）しかないため、
フレーム数と合わせて時間表示があった方が利便性が高くなると思います。

2. 4分、8分、16分なら視覚的にわかるのですが、
24分、32分と細かくなってくると随時切り替えながら譜面を作成することがあるため、
現在どの間隔になっているかわかるとわかりやすいのではと思いました。

**Comment by superkuppabros** [comment]
https://github.com/superkuppabros/danoni-editor/pull/24/commits で一部対応しました。
とりあえず現在位置の時間やフレーム数を表示するようにしました。

入力間隔のフレーム数については未実装ですが、一応必要になりそうな部分はカバー出来ている気もします。

**Comment by superkuppabros** [comment]
https://github.com/superkuppabros/danoni-editor/pull/24/ で一部対応しました。
一旦現在位置の時間やフレーム数を表示するようにしました。

間隔単位でのフレーム数表記については、表記場所などの関係で後に回しています。

**Comment by superkuppabros** [comment]
入力間隔表示について https://github.com/superkuppabros/danoni-editor/commit/03c6937241fcfb2f93beef9b44d60c803502fbf9 で対応しました。

**Comment by superkuppabros** [comment]
小節数はページ(の2倍)と対応しているので入れなくて良いと思っています。
一旦このIssueは閉じることにします。
