### ISSUE TITLE
4分譜面の作成機能

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#14]
## 要望内容
1. 現在設定されているFirstNumberとBPM設定に応じて、4分譜面を作成できる機能が欲しいです。
出力する小節数は別途指定できるようにします。

## 機能を必要とする理由
1. ダンおに本体とエディターが異なるため、
タイミングを測るために4分譜面を作成することが多いです。
他のダンおにエディターでも標準実装しているため、Issueとして上げておきます。

## 補足
- 欲を言えば、譜面が置かれている範囲は譜面を、それ以外の範囲は4分譜面を出力してマージできるようにするとより良いと思います。（優先度は低め）

**Comment by superkuppabros** [comment]
https://github.com/superkuppabros/danoni-editor/pull/19 にて一部対応。

現時点では、出力ページ数は最も後ろにある有効なページ+20ページとしました。
有効なページとは、ノーツまたは速度変化コマが1つ以上含まれているページのこと。
また、パターンもエディタの一番左のノーツで固定しています。

**Comment by cwtickle** [comment]
確認しました！ありがとうございます。
将来的には、キー毎にパターンを変えられるようにした方が良いかもしれませんが、
当面はこれで良いと思います。

**Comment by cwtickle** [comment]
キー毎にパターンを変えられるようにするのは別件のため、
この件としてはクローズしておきます。ありがとうございました m(_ _)m
