### ISSUE TITLE
楽曲再生タイミングがFirst Numberをずらした分ずれて再生される

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#15]
## 不具合内容
1. 初期の状態の場合、楽曲が200フレームで開始するようになっています。
しかし、開始位置に応じてFirst Numberを変えた状態で楽曲を再生すると
楽曲がFirst Numberをずらした分ずれて再生されます。

## 本来想定される動作
1. First Numberの変更により、楽曲の再生タイミングが変わらないようにする。
※BPMを途中で変更する場合はFirst Numberが複数になるので、
　最初のFirst Numberのみ別で持っておくといった対応が必要になると思いました。

## 確認環境
- エディターバージョン：2.00β
- 確認したキー数：12key
- Windows 10 (x64) 1909、Chrome 85 (beta)

**Comment by superkuppabros** [comment]
https://github.com/superkuppabros/danoni-editor/pull/17 にて対応。

Adjustment: 全体調整用のオーバーヘッド、
StartNum: 音楽再生位置
としました。
FirstNum = Adjustment + StartNum となります。

**Comment by cwtickle** [comment]
早速ありがとうございます！
ただ、別件で問題が発生しています。内容が違うので別Issueで上げてみます。
