### ISSUE TITLE
[bug] StartNum, Adjustmentがどちらも有効な場合にフレーム数計算がおかしくなる

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#20]
## 不具合内容
1. StartNum, Adjustmentがどちらも0より大きい場合、フレーム数計算が
文字列結合されたような挙動になります。
#17 の修正の中で、adjustmentとtiming.startNumを足し算している箇所
（ScoreConverter.ts）が怪しそうです。

### 参考セーブデータ
```
{"keyNum":12,"adjustment":"200","timings":[{"label":1,"startNum":"51","bpm":140}],"scores":[{"keyNum":12,"notes":[[192],[],[],[],[],[],[],[192],[],[],[],[]],"freezes":[[],[],[],[],[],[],[],[],[],[],[],[]],"speeds":[]},{"keyNum":12,"notes":[[192],[0],[],[],[],[192],[],[],[],[],[],[]],"freezes":[[],[],[],[],[],[],[],[],[],[],[],[]],"speeds":[]},{"keyNum":12,"notes":[[],[],[],[0],[],[192],[],[192],[],[],[],[]],"freezes":[[],[],[],[],[],[],[],[],[],[],[],[]],"speeds":[]},{"keyNum":12,"notes":[[192],[0],[],[],[],[192],[],[],[],[],[],[]],"freezes":[[],[],[],[],[],[],[],[],[],[],[],[]],"speeds":[]},{"keyNum":12,"notes":[[144],[192],[],[0],[],[96],[],[],[],[],[],[]],"freezes":[[],[],[],[],[],[],[],[],[],[],[],[]],"speeds":[]}]}
```

## 本来想定される動作
1. StartNum, Adjustmentの値によらず、数値と扱われて計算される。

## 確認環境
エディターバージョン：2.1.0β
確認したキー数：12key
Windows 10 (x64) 1909、Chrome 85 (beta)

**Comment by cwtickle** [comment]
（補足）
こちらでラベルが付けられないようなので、タイトルに表示しています。
必要に応じてラベルを付けて頂いて問題ありません。

**Comment by superkuppabros** [comment]
すべての入力値が文字列として扱われているのが原因でした。
https://github.com/superkuppabros/danoni-editor/commit/e57540df8f61f745d949a2e29d3a4271043ebc11 で対応しました。

**Comment by cwtickle** [comment]
ありがとうございます、直っていることを確認しました。
クローズしておきます。
