### ISSUE TITLE
[proposed] Adjustmentの名称変更

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#21]
## 要望内容
- Ver2.1.0βで実装されているAdjustmentの名称について、
使用用途を考慮して「BlankFrame (Number)」に変えた方が良いと思います。

## 機能を必要とする理由
- 譜面ヘッダー名で同じ名称があり（adjustment）、それと混同が生じるため。
- 使ってみた感触だと、音楽が再生されるまでのフレーム数に見えたので、
名称としては「BlankFrame」が合うと思いました。（譜面ヘッダー名とも合致します）

**Comment by superkuppabros** [comment]
BlankFrameの存在を知らなかったです…
https://github.com/superkuppabros/danoni-editor/commit/bcaafbd7dbe9416597c053332ece2704eae89efe にて対応しました。

**Comment by cwtickle** [comment]
対応ありがとうございます。
意味合いに応じた動きになっていることを確認しました。クローズします。
