### ISSUE TITLE
[proposed] Start Number -> First Numberに戻す

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#22]
## 要望内容
1. Ver2.1.0βで実装されているStart Numberについて、
Ver2.0.0β以前のFirst Number（＝Adjustment＋Start Number）に戻した方が良いと思いました。

## 機能を必要とする理由
1. StartNumberの値はあくまで楽曲再生用の都合でできた情報であり、
譜面として計算するときはFirst Numberで問題ないため。
また、現時点のフレーム数情報が2系統になることで複雑になることを懸念しています。
※先のAdjustmentに相当する値は楽曲再生機能の観点から保持すべきだと思います。

**Comment by superkuppabros** [comment]
これについて、自分は現状のAdjustment(BlankFlame) + StartNumber形式も利点があると思っています。具体的には、ラベルが多くついている譜面に対し一括でFirstNumberを変更出来る点です。
ただし、複雑であることに異論はないので、戻すかあるいはFirstNumberをどこかに表示するかで対処したいと考えています。

**Comment by cwtickle** [comment]
確かに、既存のエディターで変則テンポを制御する際、
一括変更する方法は（一部の他のエディターを除いて）無いですね。
そういう意味では、First Number相当の値をどこかに表示するのも一つの方法だと思います。

この辺りは慣れの部分もあると思うので、実際に譜面を作ってみて良さそうな方法があれば、
またIssueに上げてみることにします。

**Comment by cwtickle** [comment]
WikiやReadmeにも説明書きがあるので、一旦このIssueはクローズしておきます。
（Wikiに2ページほど新規に作成してみました、よろしくお願いします。）
