### ISSUE TITLE
[proposed] 選択させる必要のない箇所の選択無効化

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#33]
## 要望内容
- CSSの `user-select: none` を選択が不要な項目（・ボタン）に
適用するようにした方が良いと思います。
https://developer.mozilla.org/ja/docs/Web/CSS/user-select

## 機能を必要とする理由
- 意図しないコピーの抑止のため。

## 補足
- 直接的な機能ではないため、優先度は低めで構いません。

**Comment by superkuppabros** [comment]
https://github.com/superkuppabros/danoni-editor/commit/73da1484d4295b418f0282e92c873774ae6ac3bb で対応しました。
2.4.1βをリリースしています。

**Comment by cwtickle** [comment]
確認しました！ありがとうございます。クローズしておきます。
