### ISSUE TITLE
[proposed] 時間軸に対するスクロール方向の制御オプション

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#34]
## 要望内容
- 現状、エディターの時間軸に対するスクロール方向が下から上になるようになっていますが、
オプションにより、時間軸方向を逆にできるようにしたいです。

## 機能を必要とする理由
- 従来のダンおにのエディターの時間軸に対するスクロール方向は逆になっています。
今後このエディターを使う方や、合作でこのエディターを共用する場合に
混乱が生じないようにするのが理由です。

## 補足
- エディターの見た目と裏で持っている値を使い分ける必要がありそうなので
簡単ではないのは理解していますが、
多分自分が上げなくても他の人がリクエストしそうな内容なので上げておきます。

**Comment by superkuppabros** [comment]
#36 で対応しました。

**Comment by cwtickle** [comment]
仕事早い＼(^o^)／
確認しました、ありがとうございます m(_ _)m
