### ISSUE TITLE
[others] Wikiの活用

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#35]
## 要望内容
- 機能追加ではないのですが、readmeの記載が増えてきたので
Github Wikiを活用しても良いのではと思いました。
- オプショナルな機能の活用法やセーブデータの出力仕様など、
readmeに書ききれない内容をTipsとしてまとめるようにします。

## 補足
- Settingsにある「Restrict editing to collaborators only」のチェックを外せば、
所有者以外でもWikiの編集ができます。
※ページ作成用のテンプレートがあった方がいいかもしれません。

**Comment by superkuppabros** [comment]
とりあえず長くなっていたバージョン周りを移管してみました。
wikiの編集権限は公開にしました。

その他の項目は少しずつ書いていきます…

**Comment by cwtickle** [comment]
ありがとうございます！
こちらも書けるところがあれば追加していくようにします。
Issueとしてはクローズしておきます。
