### ISSUE TITLE
[proposed] セーブファイル内のデータを参照して自動でキー数を設定

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#37]
## 要望内容
1. タイトル画面でキー数を設定しなくても、
セーブファイル内のデータを参照して、自動でキー数を設定できるようにしたいです。
（セーブファイル内のデータを優先）

## 機能を必要とする理由
1. タイトル画面が常時5keyになっているため、
5key以外の譜面を作成する場合には毎回キー数を選択し直す必要があります。
その間違いを軽減することが目的です。

## 補足
- 途中でキー数を変更したい場合にどうかな？と思いましたが
それは今後、レーンコピーなどが実装された後に考えるべきかなと思ったので
一旦はセーブデータのキー数を優先する方向で良いと思います。

**Comment by superkuppabros** [comment]
#40 で対応しました。
セーブファイル内にキー種をもたせるようにしています・

**Comment by cwtickle** [comment]
確認しました、ありがとうございます！
（セーブデータのkeyNumはキー数では無かったのか＼(^o^)／）
