### ISSUE TITLE
[proposed] 譜面ファイルの名称変更

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#38]
## 要望内容
1. タイトル画面に表示されている「譜面ファイルをドロップ」について、
実際にはエディターのロード用テキストデータのため、
「エディター用テキスト」や「セーブファイル」など適切な名前に変えた方が良いと思います。

## 機能を必要とする理由（名称変更理由）
1. ダンおにで譜面ファイルと言えば「dos.txt」のような譜面データ本体を指すため。

**Comment by superkuppabros** [comment]
c3737c36090a4ecbfd6a80111bc06165b6ecd86c で対応しました。

**Comment by cwtickle** [comment]
ありがとうございます！　確認しました。
クローズしておきます。
