### ISSUE TITLE
[proposed] LocalStorageにリカバリーデータを保存する機能

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#39]
## 要望内容
- `[GO]`ボタンを押した後、譜面データをクリップボードにコピーするのと同時に、
バックグラウンドでLocalStorageにセーブデータを保存しておくようにしたいです。

## 機能を必要とする理由
- 何らかの事情でブラウザが落ちたとき、`[SAVE]`ボタンを押し忘れたときの復旧手段として準備します。

## 補足
- バックグラウンドで保存したデータをどのようにロードさせるかは別途考える必要があります。
- できるなら、3世代程度残せるようにした方が良いかもしれません。

**Comment by superkuppabros** [comment]
#41 で対応しました。
現状複数譜面の保存はしない作りです。2世代前のデータにアクセスするケースが多くなさそうで、選ぶステップの分だけ手間になりそうだったので実装は今の所考えていません。

**Comment by cwtickle** [comment]
ありがとうございます！
リカバリーデータは確かに複数だとわかりにくいですね、１つで良いと思います。
クローズしておきますー
