### ISSUE TITLE
[proposed] 小節（ページ）の途中挿入

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#42]
## 要望内容
- 小節（ページ）を間に挿入したり、カットして詰める機能が欲しいです。

## 機能を必要とする理由
- 細かいBPM変化があり、途中に挟む必要が出てきたときに、
間に小節やページを挿入できるようにした方が便利だと思います。

## 補足
- カットして詰める場合、途中にノートがある場合は警告を入れた方が親切かもしれません。

**Comment by cwtickle** [comment]
いろいろIssueを投げてしまいすみません＼(^o^)／
お時間のある時で構いませんので、よろしくお願いします m(_ _)m

**Comment by superkuppabros** [comment]
#46 で対応しました。
挿入、削除時にそれより後ろのラベルの扱いをどうするか悩みましたが、とりあえず後ろのラベルを1pずつずらす処理を挟んでいます。

**Comment by cwtickle** [comment]
ありがとうございます！
一通り確認した限りでは問題なさそうなので、この件はクローズします。
