### ISSUE TITLE
[proposed] 対応キーの画面表示

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#47]
## 要望内容
- キー別にノート入力が異なるので、
画面下側に対応キーを表示できるようにした方が良いかもしれません。

## スクリーンショット
![image](https://user-images.githubusercontent.com/44026291/85925920-8d382300-b8d6-11ea-837b-3e70703ba04e.png)

## 機能を必要とする理由
- 矢印キーなど、割り当てできないキーには別キーが割り当てられており、
直感的にわからない可能性があるため。

## 補足
- 代替キーの表示は「8 (9)」みたいに表示できると良さそうです。

**Comment by superkuppabros** [comment]
#49 で対応しました。
代替キー表示すると画面が煩い感じだったのでメインのキーのみ表示としています。

**Comment by cwtickle** [comment]
ありがとうございます！
対応キーがわかりやすくなり、使いやすくなったと思います。
クローズしておきます ｍｍ
