### ISSUE TITLE
[proposed] 初回エディター画面表示時の挙動改善

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#51]
## 要望内容
- タイトル画面とエディター画面のページが異なるため、現状は画面が移った際にノート表示エリアにフォーカスが当たらず、一度クリックが必要となっています。
これを改善したいです。

### 改善案
1. エディター画面移動後のみ、ノート配置エリア(Start Numberやページ移動ボタンなどが配置されているエリアは除きます)に半透明の黒マスク(ボタン)を掛け、「ここをクリックして開始します」といった文言を表示するようにします。
黒マスクをクリックすると、マスクが外されてノート配置エリアにフォーカスが当たる仕組みにします。

2. エディター画面移動後、自動でノート配置エリア側のフォーカスを有効にします。

## 機能を必要とする理由
- エディター画面移動後、クリックが必要なことが示されていないため、画面移動時にキー操作を始めてしまい反応しない、といったことがたまにあります。

## 補足
- 改善案を2つ書いていますが、個人的には前者の案が良いと思います。

**Comment by superkuppabros** [comment]
https://github.com/superkuppabros/danoni-editor/commit/11e3d2d53617fd8fb27b48ee1207d8a055f6c431 で対応しました。

元々2になっているつもりだったので、ここではそのような変更にしています。

**Comment by cwtickle** [comment]
動作確認しました、ありがとうございますｍｍ
