### ISSUE TITLE
クリックモードの導入

### ISSUE THREAD

**Issue by superkuppabros** [superkuppabros/danoni-editor#52]
ノーツぽちぽちするのをクリックでも出来ると嬉しいかも。
特にスマホでできそうなのが偉い。

**Comment by cwtickle** [comment]
クリックでスマホで作譜できるのは便利ですね。
パソコンとやり取りする際に、ファイルのやり取りをどうするかという問題が出てきそうなので、セーブファイルを作ってメールアドレスを指定して飛ばす機能とかがあると良さそうです。

またスマホで作成するなら、保存先のデフォルトはローカルストレージにするといった工夫も要りそうです。
