### ISSUE TITLE
[proposed] 譜面復元データ（セーブデータ復元用基礎データ）の出力

### ISSUE THREAD

**Issue by cwtickle** [superkuppabros/danoni-editor#55]
## 要望内容
- セーブデータを紛失することがあるため、
譜面データと合わせて、復元できる最小限のデータを出力できるようにしたいです。
- 譜面データと一体化させることで、後々の譜面復元に役立てます。

### 参考
- エディター特性があるので、下記にする必要はないのですが、
Cross Walkerのエディター（Flash製）で出力している例です。
```
&first_num=770,1770&haba_num=10,8&haba_page_num=0,3&rhythm_num=&label_num=0&beat_num=4&
```
- 現在のエディター仕様であれば、以下の項目の保持が考えられます。
(例：キー数、StartNumber、BPM、StartNumber/BPMを変更したページ)

## 機能を必要とする理由
- ダンおにの場合、譜面データはオブジェクトのタイミングをフレーム数で示しているだけにすぎず、
BPM変化した場合、譜面データから逆算してセーブデータを再現することが難しいため。

**Comment by superkuppabros** [comment]
大変遅くなりましたが、#58 で実装しましたのでissueはcloseします。
